import { gameDb } from '../../../db/game';
export const dynamic = 'force-dynamic';
type Player={id:string,name:string,wins:number};
type Room={code:string,host:string,players:Player[],phase:string,round:number,go:number,taps:Record<string,number>,winner:string|null,result:string};
const cors={'Access-Control-Allow-Origin':'https://masi196.github.io','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400'};
export async function OPTIONS(){return new Response(null,{status:204,headers:cors});}
function json(data:any,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...cors}})}
function view(r:Room){const {go,...safe}=r;return {...safe,phase:r.phase==='playing'?(Date.now()>=go?'green':'red'):r.phase,serverTime:Date.now()};}
function settle(r:Room){if(r.phase!=='playing')return;const now=Date.now();if(Object.keys(r.taps).length<r.players.length&&now<r.go+6500)return;
const valid=r.players.filter(p=>r.taps[p.id]>=0).sort((a,b)=>r.taps[a.id]-r.taps[b.id]);
r.phase='result'; r.winner=null;
if(!valid.length){r.result='No valid reactions. Try another round.';return;}
if(valid[1]&&r.taps[valid[0].id]===r.taps[valid[1].id]){r.result='Exact tie! Replay the round. No point awarded.';return;}
const p=valid[0];p.wins++;r.winner=p.id;r.result=p.name+' wins the round';if(p.wins>=3){r.phase='finished';r.result=p.name+' wins the match!';}}
export async function GET(req:Request){try{const code=new URL(req.url).searchParams.get('code')?.toUpperCase();if(!code)return json({error:'Enter a room code.'},400);const db=gameDb();for(let i=0;i<12;i++){const row:any=await db.prepare('SELECT data, revision FROM rooms WHERE code = ?').bind(code).first();if(!row)return json({error:'Room not found. Check the code.'},404);const r:Room=JSON.parse(row.data);const old=JSON.stringify(r);settle(r);if(old!==JSON.stringify(r)){const result=await db.prepare('UPDATE rooms SET data = ?, revision = revision + 1 WHERE code = ? AND revision = ?').bind(JSON.stringify(r),code,row.revision).run();if(!result.meta.changes)continue;}return json(view(r));}return json({error:'Room is busy. Try again.'},409);}catch(e){console.error(e);return json({error:'Connection problem. Please try again.'},503);}}
export async function POST(req:Request){try{const b:any=await req.json();const db=gameDb();if(b.action==='create'){const name=String(b.name||'').trim().slice(0,20);if(!name)return json({error:'Enter your name.'},400);for(let i=0;i<8;i++){const bytes=crypto.getRandomValues(new Uint8Array(6));const code=Array.from(bytes,x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%32]).join('');const id=crypto.randomUUID();const r:Room={code,host:id,players:[{id,name,wins:0}],phase:'lobby',round:0,go:0,taps:{},winner:null,result:''};const res=await db.prepare('INSERT OR IGNORE INTO rooms (code,data,revision) VALUES (?,?,0)').bind(code,JSON.stringify(r)).run();if(res.meta.changes)return json({room:view(r),id});}throw Error('Code collision');}
const code=String(b.code||'').toUpperCase();const joinId=crypto.randomUUID();for(let i=0;i<16;i++){const row:any=await db.prepare('SELECT data,revision FROM rooms WHERE code = ?').bind(code).first();if(!row)return json({error:'Room not found. Check the code.'},404);const r:Room=JSON.parse(row.data);settle(r);const player=r.players.find(p=>p.id===b.id);let id=b.id;
if(b.action==='join'){if(r.phase!=='lobby')return json({error:'This match has started. Join the next match.'},400);if(r.players.length>=8)return json({error:'Room is full (8 players).'},400);const name=String(b.name||'').trim().slice(0,20);if(!name)return json({error:'Enter your name.'},400);id=joinId;r.players.push({id,name,wins:0});}
else {if(!player)return json({error:'Please rejoin the room.'},403);
if(b.action==='start'||b.action==='next'){if(b.id!==r.host)return json({error:'Only the host can start rounds.'},403);if(r.players.length<2)return json({error:'Wait for at least two players.'},400);if(!['lobby','result'].includes(r.phase))return json({error:'Round already started.'},400);r.phase='playing';r.round++;r.go=Date.now()+2500+crypto.getRandomValues(new Uint32Array(1))[0]%5000;r.taps={};r.winner=null;r.result='';}
else if(b.action==='tap'){if(r.phase!=='playing'||b.round!==r.round)return json({room:view(r),id});if(!(b.id in r.taps)){const elapsed=Number(b.elapsed);r.taps[b.id]=b.early||Date.now()<r.go?-1:(Number.isFinite(elapsed)&&elapsed>=0&&elapsed<=6500?Math.round(elapsed):-1);settle(r);}}
else if(b.action==='rematch'){if(b.id!==r.host||r.phase!=='finished')return json({error:'Wait for the host to start a rematch.'},400);r.players.forEach(p=>p.wins=0);r.phase='lobby';r.round=0;r.taps={};r.winner=null;r.result='';}
else return json({error:'Unknown action.'},400);}
const res=await db.prepare('UPDATE rooms SET data = ?, revision = revision + 1 WHERE code = ? AND revision = ?').bind(JSON.stringify(r),code,row.revision).run();if(res.meta.changes)return json({room:view(r),id});}return json({error:'Room busy. Please try again.'},409);}catch(e){console.error(e);return json({error:'Connection problem. Please try again.'},503);}}
